version: "3.8"

services:
    php:
        build: .
        ports:
            - "86:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql

    mysql:
        image: mysql:9.2.0-oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: ql_cuahanggiay
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command: --sql_mode="STRICT_TRANS_TABLES"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./DatabaseServer/ql_cuahanggiay.sql:/docker-entrypoint-initdb.d/ql_cuahanggiay.sql:ro
            - ./php.ini:/usr/local/etc/php/php.ini:ro

volumes:
    mysql-data:
